version: '3.1'

networks:
  javaweek:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: javaweek
      POSTGRES_PASSWORD: postgres
    volumes:
      - javaweekdb:/var/lib/postgresql/data
    networks:
      - javaweek

volumes:
  javaweekdb:
